version: '3'

tasks:
  daemon:build:
    sources:
      - 'internal/**/*.go'
      - 'cmd/daemon/main.go'
    cmds:
      - go build -o out/daemon cmd/daemon/main.go
  daemon:run:
    deps:
      - daemon:build
    cmds:
      - ./out/daemon

  tui:build:
    sources:
      - 'internal/**/*.go'
      - 'cmd/daemon/main.go'
    cmds:
      - go build -o out/tui cmd/tui/main.go
  tui:run:
    deps:
      - tui:build
    env:
      BUBBLETEA_LOG: tui.log
    cmds:
      - ./out/tui
    interactive: true

  fmt:
    sources:
      - '**/*.go'
    cmds:
      - go fmt ./...

  test:
    sources:
      - '**/*.go'
    cmds:
      - go test ./...

  dev:
    cmds:
      - zellij action new-tab --layout dev.kdl --name dev
