version: '3'

tasks:
  build:
    sources:
      - '**/*.go'
    cmds:
      - go build -o out/main cmd/main.go
  daemon:
    deps:
      - build
    cmds:
      - ./out/main daemon
  fmt:
    sources:
      - '**/*.go'
    cmds:
      - go fmt ./...

  dev:
    cmds:
      - zellij action new-tab --layout dev.kdl --name dev
