version: '3'

includes:
  plugin:
    taskfile: zellij-plugin/Taskfile.yml
    dir: ./zellij-plugin
  daemon:
    taskfile: Taskfile.daemon.yml
  tui:
    taskfile: Taskfile.tui.yml

tasks:
  go:fmt:
    sources:
      - '**/*.go'
    cmds:
      - go fmt ./...
  go:test:
    sources:
      - '**/*.go'
    cmds:
      - go test ./...

  fmt:
    cmds:
      - task: go:fmt
      - task: plugin:fmt

  dev:
    cmds:
      - zellij action new-tab --layout dev.kdl --name dev
